name: Validate / Publish helm charts

on:
  release:
    types: [published]
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
    inputs:
      IGNORE_CHARTS:
        description: 'Provide list of charts to be ignored separated by pipe(|)'
        required: false
        default: 'activemq-artemis | admin-hotlist | admin-service | admin-ui | apitestrig | artifactory | auditmanager | authdemo | authmanager | biosdk-service | clamav | conf-secrets | config-server | credential | credentialrequest | databreachdetector/templates | datashare | dslorchestrator | gc-util | ida-auth | ida-internal | ida-otp | identity | idgenerator | idrepo-saltgen | keycloak-init | keygen | keymanager | masterdata-loader | masterdata | minio-client-util | mock-abis | mock-mv | mock-smtp | mosip-file-server | notifier | opencrvs-mediator | otpmanager | packetcreator | packetmanager | partner-onboarder | pmp-ui | pms-migration-utility | pms-partner | pms-policy | postgres-init | postgres-upgrade | prereg-application | prereg-batchjob | prereg-booking | prereg-captcha | prereg-datasync | prereg-gateway | prereg-ui | pridgenerator | print | regclient | regproc-camel | regproc-group1 | regproc-group2 | regproc-group3 | regproc-group4 | regproc-group5 | regproc-group6 | regproc-group7 | regproc-notifier | regproc-opencrvs | regproc-pktserver | regproc-reprocess | regproc-salt | regproc-status | regproc-trans | regproc-workflow | reporting-init | reporting | resident-ui | resident | restart-cron | ridgenerator | softhsm | status-check | syncdata | tusd | uitestrig | vid | websub-consolidator | websub'
        type: string
      CHART_PUBLISH:
        description: 'Chart publishing to gh-pages branch'
        required: false
        default: 'NO'
        type: string
        options:
          - YES
          - NO
      INCLUDE_ALL_CHARTS:
        description: 'Include all charts for Linting/Publishing (YES/NO)'
        required: false
        default: 'NO'
        type: string
        options:
          - YES
          - NO
  push:
    branches:
      - niradev-1.2.0.1-N1
    paths:
      - 'charts/landing-page/'

jobs:
  chart-lint-publish:
    uses: mosip/kattu/.github/workflows/chart-lint-publish.yml@master
    with:
      CHARTS_DIR: charts
      CHARTS_URL: https://niragit.github.io/mosip-helm
      REPOSITORY: mosip-helm
      BRANCH: gh-pages
      INCLUDE_ALL_CHARTS: "${{ inputs.INCLUDE_ALL_CHARTS || 'NO' }}"
      IGNORE_CHARTS: "${{ inputs.IGNORE_CHARTS ||'\"\"' }}"
      CHART_PUBLISH: "${{ inputs.CHART_PUBLISH || 'YES' }}"
      LINTING_CHART_SCHEMA_YAML_URL: "https://raw.githubusercontent.com/mosip/kattu/master/.github/helm-lint-configs/chart-schema.yaml"
      LINTING_LINTCONF_YAML_URL: "https://raw.githubusercontent.com/mosip/kattu/master/.github/helm-lint-configs/lintconf.yaml"
      LINTING_CHART_TESTING_CONFIG_YAML_URL: "https://raw.githubusercontent.com/mosip/kattu/master/.github/helm-lint-configs/chart-testing-config.yaml"
      LINTING_HEALTH_CHECK_SCHEMA_YAML_URL: "https://raw.githubusercontent.com/mosip/kattu/master/.github/helm-lint-configs/health-check-schema.yaml"
    secrets:
      TOKEN: ${{ secrets.ACTION_PAT }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
